# Generated by Django 2.1.8 on 2019-04-27 21:26
# Fixed for Django 5: use AddIndex instead of removed AlterIndexTogether.
# Both Meta.indexes are added here with their final names so migration 0010
# does not need to perform a RenameIndex.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0007_add_timestamp_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient', 'unread'],
                name='notificatio_recipie_8bedf2_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['recipient', 'deleted'],
                name='notification_recipient_deleted_idx',
            ),
        ),
    ]
