# Generated by Django 4.2.20 on 2025-04-02 14:53
# Fixed for Django 5: the RenameIndex is no longer needed because migration 0008
# now adds both compound indexes with their final names directly via AddIndex,
# bypassing the removed AlterIndexTogether / unnamed-index mechanism.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_alter_notification_options_and_more"),
    ]

    operations = []
